import type { FeatureCollection, MultiPolygon, Polygon } from "geojson";
import raw from "./nypdPrecincts.json";

// Simplified NYPD precinct boundary polygons (from NYC DCP's "Police Precincts"
// dataset), each tagged with the NypdStation id it belongs to. Generated by
// scripts/build_nypd_precincts.py.
export const nypdPrecincts = raw as unknown as FeatureCollection<
  Polygon | MultiPolygon,
  { stationId: string; precinct: string }
>;
